//! `fuzz`: the differential fuzzer. Wires `reference` and `engine` to the
//! same command stream (`harness`), generated by a shadow-book-backed
//! generator whose model of liveness is exact by construction
//! (`generator`), because it is not a model at all -- it is a query
//! against a real, correctly-behaving `reference::RefBook`.

#![forbid(unsafe_code)]

mod generator;
mod harness;

pub use generator::{CommandMix, Generator, Stats};
pub use harness::{Divergence, Failure, Harness};

use types::Config;

/// The `Config` both runners and the calibration mutations use. Small
/// band, small arena, and -- deliberately smaller than
/// `types::DEFAULT_CONFIG`'s -- a tiny retirement window, so id reuse
/// (the F-001 scenario) is evicted into and back out of constantly rather
/// than being a rare event a long run might never reach.
pub const FUZZ_CONFIG: Config = Config { n_ticks: 256, capacity: 64, id_retirement_window: 32 };
